FOS.Web.UI/Controllers/API/ComplaintController.cs
using FOS.DataLayer;
using FOS.Shared;
using Shared.Diagnostics.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;


namespace FOS.Web.UI.Controllers.API
{
    public class ComplaintController : ApiController
    {
        FOSDataModel db = new FOSDataModel();

        public IHttpActionResult GetSOComplaints(int soId)
        {
            try
            {
                var list = db.Complaints.Where(d => d.SaleOfficerId == soId && d.Status == (int)StatusEnum.Pending).ToList();
                if (list != null)
                {
                    return Ok(new
                    {
                        Complaints = list.Select(d => new
                        {
                            d.ComplaintID,
                            d.Title,
                            d.Detail,
                            d.ComplaintType,
                            d.DueDate,
                            //DueDateLong = d.DueDate.Ticks,
                            RetailerName = d.Retailer.Name,
                            d.Priority,
                            d.Status,
                            d.Remarks
                        }).OrderBy(d => d.DueDate)
                    });
                }
                else
                {
                    return Ok(new
                    {
                        Complaints = new { }
                    });
                }

            }
            catch (Exception ex)
            {
                Log.Instance.Error(ex, "GetSOComplaints List API Failed");
                return Ok(new
                {
                    Complaints = new { }
                });
            }
        }
        [System.Web.Http.HttpPost]
        public IHttpActionResult UpdateComplaint(ComplaintsModel model)
        {
            try
            {
                if (FOS.Web.UI.Common.Token.TokenAttribute.IsTokenValid(model.Token))
                {
                    Complaint complaint = db.Complaints.Where(u => u.ComplaintID == model.ComplaintId).FirstOrDefault();

                    if (complaint != null)
                    {
                        complaint.Remarks = model.Remarks;
                        complaint.UpdatedBy = model.UpdatedBy;
                        complaint.RemUpdatedOn = DateTime.Now;

                        // Add Token Detail ...
                        TokenDetail tokenDetail = new TokenDetail();
                        tokenDetail.TokenName = model.Token;
                        tokenDetail.Action = "Update Complaint";
                        tokenDetail.ProcessedDateTime = DateTime.Now;
                        db.TokenDetails.Add(tokenDetail);
                        //END

                        db.SaveChanges();
                    }
                    else
                    {
                        return Ok(new
                        {
                            status = new CheckInLatLongResp
                            {
                                code = "400",
                                message = "Complaint not found in update complaint API"
                            }
                        });
                    }
                    
                    

                    return Ok(new
                    {
                        status = new CheckInLatLongResp
                        {
                            code = "200",
                            message = "Complaint updated successfully"
                        }
                    });
                }
                else
                {
                    return Ok(new
                    {
                        status = new CheckInLatLongResp
                        {
                            code = "400",
                            message = "Authentication failed in update complaint API"
                        }
                    });
                }
            }
            catch (Exception ex)
            {
                Log.Instance.Error(ex, "Update Complaint API Failed");
                return Ok(new
                {
                    status = new CheckInLatLongResp
                    {
                        code = "400",
                        message = "Update Complaint API Failed"
                    }
                });
            }
        }
    }
    public class ComplaintsModel
    {
        public int ComplaintId { get; set; }
        public string Remarks { get; set; }
        public int UpdatedBy { get; set; }
        public string Token { get; set; }
    }
}

FOS.Web.UI/Controllers/API/DealerController.cs
using FOS.DataLayer;
using Shared.Diagnostics.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;


namespace FOS.Web.UI.Controllers.API
{
    public class DealerController : ApiController
    {
        FOSDataModel db = new FOSDataModel();

        public IHttpActionResult GetSODealers(int regionalHeadId)
        {
            try
            {
                int soId = regionalHeadId; // now we are getting SOID instead of regionalHeadId
                List<int> soDealerIds = db.Retailers.Where(p => p.SaleOfficerID == soId
                && !p.IsDeleted && p.IsActive && p.Status).Select(x => x.DealerID ?? 0).ToList<int>();
                return Ok(new
                {
                    Dealers = db.Dealers.Where(d => soDealerIds.Contains(d.ID)
                    && d.IsActive && !d.IsDeleted).Select(d => new
                    {
                        d.ID,
                        d.Name
                    }).OrderBy(d => d.Name)
                });
                //return Ok(new
                //{
                //Dealers = db.Dealers.Where(d => d.RegionalHeadID == regionalHeadId
                //&& d.IsActive && !d.IsDeleted).Select(d => new
                //{
                //    d.ID,
                //    d.Name
                //}).OrderBy(d => d.Name)
                //});

            }
            catch (Exception ex)
            {
                Log.Instance.Error(ex, "GetSODealers API Failed");
                return Ok(new
                {
                    Dealers = new { }
                });
            }
        }

        public IHttpActionResult GetSODealersBirthdaysList(int soId)
        {
            try
            {
                DateTime fromDate = DateTime.Today.AddDays(-3);
                DateTime toDate = DateTime.Today.AddDays(4);
                List<int> soDealerIds = db.Retailers.Where(p => p.SaleOfficerID == soId
                && p.IsActive && p.Status && !p.IsDeleted
                ).Select(x => x.DealerID ?? 0).ToList<int>();
                return Ok(new
                {
                    Dealers = db.Dealers.Where(d => soDealerIds.Contains(d.ID)
                    && d.IsActive && !d.IsDeleted
                    && d.Birthday >= fromDate && d.Birthday <= toDate).Select(d => new
                    {
                        d.ID,
                        d.Name,
                        d.Birthday
                    }).OrderBy(d => d.Name)
                });

            }
            catch (Exception ex)
            {
                Log.Instance.Error(ex, "GetSODealersBirthdaysList API Failed");
                return Ok(new
                {
                    Dealers = new { }
                });
            }
        }
        public IHttpActionResult GetSODealersList(int soId) // now its of no use for time being as above one is used instead of it.
        {
            try
            {
                List<int> soDealerIds = db.Retailers.Where(p => p.SaleOfficerID == soId
                && p.IsActive && p.Status && !p.IsDeleted
                ).Select(x => x.DealerID ?? 0).ToList<int>();
                return Ok(new
                {
                    Dealers = db.Dealers.Where(d => soDealerIds.Contains(d.ID)
                    && d.IsActive && !d.IsDeleted).Select(d => new
                    {
                        d.ID,
                        d.Name
                    }).OrderBy(d => d.Name)
                });

            }
            catch (Exception ex)
            {
                Log.Instance.Error(ex, "GetSODealersList API Failed");
                return Ok(new
                {
                    Dealers = new { }
                });
            }
        }
        public IHttpActionResult GetSODealersBirthdays(int soId, int regionalHeadId)
        {
            try
            {
                //var dte = DateTime.Now.Date;
                List<int> soRetailers = db.Retailers.Where(p => p.SaleOfficerID == soId
                && p.IsActive && p.Status && !p.IsDeleted
                ).Select(pp => pp.ID).ToList<int>();
                var DealersBirthdays = db.Dealers.Where(d => d.RegionalHeadID == regionalHeadId
                && d.Planned == true
                && d.IsActive && !d.IsDeleted
                && d.Birthday == DateTime.Today).Select(d => new DBirthdaysModel
                {
                    ID = d.ID,
                    Name = d.Name,
                    Phone1 = d.Phone1,
                    Address = d.Address,
                    Birthday = d.Birthday.Value,
                    Retailers = d.Retailers,
                    Yes = false
                }).OrderBy(d => d.Name).ToList();

                foreach (var dealer in DealersBirthdays)
                {
                    List<int> dealerRetailers = dealer.Retailers.Select(k => k.ID).ToList<int>();
                    foreach (var soRet in soRetailers)
                    {
                        if (dealerRetailers.Contains(soRet))
                        {
                            dealer.Yes = true;
                        }
                    }
                }

                return Ok(new
                {
                    DealersBirthdays = DealersBirthdays.Where(dd => dd.Yes).Select(s => new
                    {
                        s.ID,
                        s.Name,
                        s.Birthday,
                        s.Phone1,
                        s.Address
                    }).ToList()
                });

            }
            catch (Exception ex)
            {
                Log.Instance.Error(ex, "GetSODealersBirthdays API Failed");
                return Ok(new
                {
                    DealersBirthdays = new { }
                });
            }
        }
    }
    public class DBirthdaysModel
    {
        public DBirthdaysModel()
        {
            this.Retailers = new HashSet<Retailer>();
        }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public bool Yes { get; set; }
        public DateTime Birthday { get; set; }

        public virtual ICollection<Retailer> Retailers { get; set; }

    }
}

FOS.Web.UI/Views/Complaint/Dealer/DealerCities.cshtml
@model FOS.Shared.DealerCityData
@{
    ViewBag.Title = "Distributor Cities";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Style/jquery-ui.min.css" rel="stylesheet" />
<script src="~/Content/Style/jquery-ui.min.js"></script> 
<!-- BEGIN PAGE HEADER-->
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN THEME CUSTOMIZER-->

        <!-- END THEME CUSTOMIZER-->
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title"></h3>
        <ul class="breadcrumb">
            <li>
                <a href="#">Manage Cities and Areas of Distributor</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>

<div class="row-fluid">
        
            @*<div class="widget-title">
                <h4>Manage Cities and Areas of Dealers</h4>
                <span class="tools">
                    @*<a href="javascript:;" class="icon-chevron-down"></a>* @
                    @ *<a href="javascript:;" class="icon-remove"></a>* @
                </span>
            </div>*@
                
    <div class="span12">
        
            <div class="control-group" style="display:none;">
                <label class="control-label">Head Type</label>
                <div class="controls">
                    <select id="Type" name="Type" disabled>
                        <option value="1">Territorial Head</option>
                    </select>
                </div>
            </div>

            @if (FOS.Web.UI.Controllers.AdminPanelController.GetRegionalHeadIDRelatedToUser() == 0)
            {
                <!-- Select RegionalHead -->
                <div class="control-group" style="margin-bottom:0px;float:left">
                    <label class="control-label">Regional Head</label>
                    <div class="controls" style="margin-left:0px">
                        @Html.DropDownListFor(model => model.RegionalHeadID, new SelectList(Model.RegionalHeads, "ID", "Name"), new { @class = "", @style = "width: 190px;" })

                        @Html.HiddenFor(model => model.HiddenRegionalHeadID)
                    </div>
                </div>
                <script>
                    $(document).ready(function () {
                        $("#HiddenRegionalHeadID").val("@FOS.Web.UI.Controllers.AdminPanelController.GetRegionalHeadIDRelatedToUser()");
                            });
                </script>
            }
            else
            {
                @Html.HiddenFor(model => model.HiddenRegionalHeadID)
                <script>
                    $(document).ready(function () {
                        $("#HiddenRegionalHeadID").val("@FOS.Web.UI.Controllers.AdminPanelController.GetRegionalHeadIDRelatedToUser()");
                    });
                </script>
            }

            <div class="control-group" style="margin-bottom:0px;margin-left:10px;float:left">
                <label class="control-label">Select Distributor</label>
                <div class="controls" style="margin-left:0px">
                    @Html.DropDownListFor(model => model.DealerID, new SelectList(Model.Dealers, "ID", "Name"), "", new { @class = "" })

                </div>
            </div>

        <div class="control-group" style="margin-bottom:0px;margin-left:10px;float:left">
            <label class="control-label" id="lblcity">Select City</label>
            <div class="controls">
                @Html.DropDownListFor(model => model.CityID, new SelectList(Model.Cities, "ID", "Name"), "", new { @class = "" })

            </div>
        </div>
        <div class="control-group" style="margin-bottom:0px;margin-top:20px;float:right">
            <div class="controls">
                <input type="button" class="btn btn-primary" value="Save" id="btnSave" onclick="saveDealerAreas();" />
            </div>
        </div>
        <div class="control-group" style="margin-bottom:0px;margin-top:20px;margin-right:20px;float:right">
            <div class="controls">
                <input type="radio" name="sel" id="rdoCity" onchange="cityWiseChange();" />Citywise
                <input type="radio" name="sel" id="rdoArea" onchange="cityWiseChange();" checked="checked" />Areawise
            </div>
        </div>
        
            
        <div id="DealerCityAreaDiv"></div>


    </div>
</div>

<script>

    function cityWiseChange() {
        
        if ($('#rdoArea').is(':checked') == true) {
            $('#CityID').show();
            $('#lblcity').show();
            $('#CityID').val(0);
            $('#DealerID').val(0);
            $('#RegionalHeadID').val(0);
            $('#RegionalHeadID').trigger('change');
        }
        else {
            $('#CityID').hide();
            $('#lblcity').hide();
            $('#CityID').val(0);
            $('#DealerID').val(0);
            $('#RegionalHeadID').val(0);
            $('#RegionalHeadID').trigger('change'); 
        }
    }
    function saveDealerAreas() {
        if ($('#RegionalHeadID').val() == 0 || $('#DealerID').val() == 0) {
            alert('There is no data to save');
            return;
        }
        if ($('#rdoArea').is(':checked') == true) {

            var DealerID = $('#DealerID').val();
            var CityID = $('#CityID').val();
            var trs = $('.table').find('tr');
            var str = '';
            for (var i = 0; i < trs.length; i++) {

                if ($(trs[i]).find('input').attr('checked') == 'checked') {
                    var cityid = $(trs[i]).find('input').attr('city-id');
                    var areaid = $(trs[i]).find('input').attr('area-id');
                    if (cityid > 0 && areaid > 0) {
                        str = str + ';' + cityid + '-' + areaid;
                    }
                }
            }

            $.ajax({
                type: "POST",
                url: "@Url.Action("SaveDealerCityAndAreas", "Dealer")",
                data: { DealerID: DealerID, cityAreas: str, CityID: CityID },
                success: function (result) {

                    if (result == "ok") {
                        alert("Saved successfully");
                        $('#CityID').val(0);
                        $("#CityID").trigger("change");
                    }
                    else if (result == "deleteok") {
                        alert("City unallocated successfully");
                        $('#CityID').val(0);
                        $("#CityID").trigger("change");
                    }
                    else {
                        alertify.error("Unable to save distributor city and areas");
                        $('#CityID').val(0);
                        $("#CityID").trigger("change");
                    }
                }
            });
        }
        else {

            var DealerID = $('#DealerID').val();
            var trs = $('.table').find('tr');
            var str = '';
            for (var i = 0; i < trs.length; i++) {

                if ($(trs[i]).find('input').attr('checked') == 'checked') {
                    var cityid = $(trs[i]).find('input').attr('city-id');
                    if (cityid > 0) {
                        str = str + ';' + cityid;
                    }
                }
            }

            $.ajax({
                type: "POST",
                url: "@Url.Action("SaveDealerCityAndAreasCitywise", "Dealer")",
                data: { DealerID: DealerID, cities: str },
                success: function (result) {

                    if (result == "ok") {
                        alert("Citywise saved successfully");
                        $('#rdoArea').attr('checked', 'checked');
                        $('#lblcity').show();
                        $('#CityID').show();
                        $('#CityID').val(0);
                        $("#CityID").trigger("change");
                    }
                    else {
                        alertify.error("Unable to save distributor cities");
                        //$('#CityID').val(0);
                        //$("#CityID").trigger("change");
                    }
                }
            });
        }
    }
    function GetDealerCityAndAreas() {
        debugger;
        if ($('#rdoArea').is(':checked') == true) {
            var DealerID = $('#DealerID').val();
            var CityID = $('#CityID').val();
            if (DealerID > 0) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("GetDealerCityAndAreas", "Dealer")",
                    data: { CityID: CityID, DealerID: DealerID },
                    success: function (result) {

                        var $el = $("#DealerCityAreaDiv");
                        $el.empty();
                        $el.append(result);
                    }
                });
            }
            else {
                var $el = $("#DealerCityAreaDiv");
                $el.empty();
            }
        }
        else {
            var DealerID = $('#DealerID').val();
            if (DealerID > 0) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("GetDealerCityAndAreasCitywise", "Dealer")",
                    data: { DealerID: DealerID },
                    success: function (result) {

                        var $el = $("#DealerCityAreaDiv");
                        $el.empty();
                        $el.append(result);
                    }
                });
            }
            else {
                var $el = $("#DealerCityAreaDiv");
                $el.empty();
            }
        }
    }

    function GetCityAndAreaList(RegionalHeadID) {

        $.ajax({
            type: "POST",
            url: "@Url.Action("GetCityListByRegionHeadIDSelectAllText", "Dealer")",
            data: { RegionalHeadID: RegionalHeadID },
            success: function (json) {

                var $el = $("#CityID");
                $el.empty(); // remove old options
                $.each(json, function (value, key) {
                    $el.append($("<option></option>").val(key.ID).text(key.Name));
                });

                //GetAreaList($("#CityID option:first").val());
            }
        });
    }

    function chkboxAllChange(chkbox) {
        if ($(chkbox).attr('checked') == 'checked') {
            // select all chckboxes
            $('.table').find('tr').each(function () {
                $(this).find('input').attr('checked', true);
            });
        }
        else {
            // un select all chkboxes
            $('.table').find('tr').each(function () {
                $(this).find('input').attr('checked', false);
            });

        }
    }

    @*function GetAreaList(CityID) {
        $.ajax({
            type: "POST",
            url: "@Url.Action("GetAreaListByCityID", "Dealer")",
            data: { CityID: CityID == null ? 0 : CityID },
            success: function (json) {

                var $el = $("#AreaID");
                $el.empty(); // remove old options
                $.each(json, function (value, key) {
                    $el.append($("<option></option>").val(key.ID).text(key.Name));
                });
            }

        });
    }*@

    function GetDealersList(regionalHeadID) {
        $.ajax({
            type: "POST",
            url: "@Url.Action("GetDealersByRegionalHeadId", "Dealer")",
            data: { RegionalHeadID: regionalHeadID },
            success: function (json) {

                var $el = $("#DealerID");
                $el.empty(); // remove old options
                $.each(json, function (value, key) {
                    $el.append($("<option></option>").val(key.ID).text(key.Name));
                });
            }

        });
    }

    $(document).ready(function () {

        var WriteCheck = "0";

        if (WriteCheck == "@HttpContext.Current.Session["WriteCheck"]") {
            // $("#btnNew").css("display", "none");
            //$("#btnNew").attr("disabled", true);
        }
        else {
        }

        $("#CityID").change(function () {
            GetDealerCityAndAreas();
        });

        $("#DealerID").change(function () {
            GetDealerCityAndAreas();
        });

        $("#RegionalHeadID").change(function () {
            $("#HiddenRegionalHeadID").val($(this).val())
            GetDealersList($(this).val());
            GetCityAndAreaList($(this).val());
            var $el = $("#DealerCityAreaDiv");
            $el.empty();

        });

        var $el = $("#DealerID");
        $el.empty(); // remove old options
        $el.append($("<option></option>").val(0).text('Select'));

        $el = $("#CityID");
        $el.empty(); // remove old options
        $el.append($("<option></option>").val(0).text('All'));

    });
</script>

@*<script type="text/javascript">

    

    function OnSuccess(response) {
        if (response == "1") {
            alertify.success("Dealer Saved Successfully");
            ClearForm();
        }
        else if (response == "0") {
            alertify.error("Unable To Save Dealer.");
        }
        else {
            alertify.error(response);
        }

    }

    function OnFailure(response) {
        if (response.status == 422) {
            var errors = JSON.parse(response.responseText);
            alertify.error(errors.errors);
        }
        else {
            alertify.error(response);
        }
    }

</script>*@