FOS.Web.UI/Controllers/API/AreasController.cs
using FOS.DataLayer;
using FOS.Setup;
using Shared.Diagnostics.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;


namespace FOS.Web.UI.Controllers.API
{
    public class AreasController : ApiController
    {
        FOSDataModel db = new FOSDataModel();

        public IHttpActionResult Get(int RegionID, int CityID)
        {
            try
            {
                if (RegionID > 0 && CityID > 0)
                {
                    //var Item = ManageArea.GetAreasForAPI(RegionID, CityID);
                    //if (Item != null && Item.Count > 0)
                    //{
                    //    return Ok(new
                    //    {
                    //        Areas = Item.Where(s => s.IsActive).Select(d => new
                    //        {
                    //            d.ID,
                    //            d.Name
                    //        }).OrderBy(d => d.Name)
                    //    });
                    //}
                }
            }
            catch (Exception ex)
            {
                Log.Instance.Error(ex, "AreaController Get API Failed");
            }

            return Ok(new
            {
                Areas = new { }
            });
        }
    }
}

FOS.Web.UI/Controllers/SetupController.cs
using FluentValidation.Results;
using FOS.DataLayer;
using FOS.Setup;
using FOS.Setup.Validation;
using FOS.Shared;
using FOS.Web.UI.Common.CustomAttributes;
using FOS.Web.UI.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace FOS.Web.UI.Controllers
{
    public class SetupController : Controller
    {
        #region SchemeInformation
        public int DeleteScheme(int schemeID)
        {
            return FOS.Setup.ManageScheme.DeleteScheme(schemeID);
        }
        public JsonResult SchemeDataHandler(DTParameters param)
        {
            try
            {
                var dtsource = new List<SchemeData>();

                dtsource = ManageScheme.GetSchemesForGrid();

                List<String> columnSearch = new List<string>();

                foreach (var col in param.Columns)
                {
                    columnSearch.Add(col.Search.Value);
                }

                List<SchemeData> data = ManageScheme.GetSchemeResult(param.Search.Value, param.SortOrder, param.Start, param.Length, dtsource, columnSearch);
                int count = ManageScheme.Count(param.Search.Value, dtsource, columnSearch);
                DTResult<SchemeData> result = new DTResult<SchemeData>
                {
                    draw = param.Draw,
                    data = data,
                    recordsFiltered = count,
                    recordsTotal = count
                };
                return Json(result);
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message });
            }
        }
        [CustomAuthorize]
        //View Work...
        public ActionResult SchemeInformation()
        {
            return View();
        }
        public JsonResult AddUpdateScheme(SchemeData tas)
        {

            try
            {
                //var serialize = JsonConvert.DeserializeObject<List<TblMasterScheme>>(cont);
                FOSDataModel dbContext = new FOSDataModel();
                ValidationResult results = new ValidationResult();
                //if (serialize != null)
                //{
                    TblMasterScheme ms = new TblMasterScheme();
                if (tas.SchemeID==0) {
                    //ms.RangeID = tas.RangeID;
                    ms.SchemeDateFrom = tas.SchemeDateFrom;
                    ms.SchemeDateTo = tas.SchemeDateTo;
                    ms.SchemeInfo = tas.SchemeInfo;
                    ms.isActive = true;
                    TblMasterScheme ms2 = dbContext.TblMasterSchemes.Where(x => x.isActive == true).FirstOrDefault();
                    ms2.isActive = false;
                    dbContext.TblMasterSchemes.Add(ms);
                    dbContext.SaveChanges();
                }
                else
                {
                    ms = dbContext.TblMasterSchemes.Where(u => u.MasterSchemeID == tas.SchemeID).FirstOrDefault();
                    ms.SchemeDateFrom = tas.SchemeDateFrom;
                    ms.SchemeDateTo = tas.SchemeDateTo;
                    ms.SchemeInfo = tas.SchemeInfo;
                    ms.isActive = true;
                    TblMasterScheme ms2 = dbContext.TblMasterSchemes.Where(x => x.isActive == true).FirstOrDefault();
                    ms2.isActive = false;
                    dbContext.SaveChanges();
                }
                //}
                return Json("1");
            }
            catch (Exception ex)
            {
                return Json("2");
            }


        }
        #endregion

        #region REGION

        [CustomAuthorize]
        //View Work...
        public ActionResult Region()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddUpdateRegion([Bind(Exclude = "TID")] RegionData newRegion)
        {
            var userID = Convert.ToInt32(Session["UserID"]);
            Boolean boolFlag = true;
            ValidationResult results = new ValidationResult();
            try
            {
                if (newRegion != null)
                {
                    if (newRegion.RegionID == 0)
                    {
                        RegionValidator validator = new RegionValidator();
                        results = validator.Validate(newRegion);
                        boolFlag = results.IsValid;
                    }

                    if (boolFlag)
                    {
                        int Response = ManageRegion.AddUpdateRegion(newRegion, userID);

                        if (Response == 1)
                        {
                            return Content("1");
                        }
                        else if (Response == 2)
                        {
                            return Content("2");
                        }
                        else
                        {
                            return Content("0");
                        }
                    }
                    else
                    {
                        IList<ValidationFailure> failures = results.Errors;
                        StringBuilder sb = new StringBuilder();
                        sb.Append(String.Format("{0}:{1}", "*** Error ***", "<br/>"));
                        foreach (ValidationFailure failer in results.Errors)
                        {
                            sb.AppendLine(String.Format("{0}:{1}{2}", failer.PropertyName, failer.ErrorMessage, "<br/>"));
                            Response.StatusCode = 422;
                            return Json(new { errors = sb.ToString() });
                        }
                    }
                }

                return Content("0");
            }
            catch (Exception exp)
            {
                return Content("Exception : " + exp.Message);
            }
        }

        //Get All Region Method...
        public JsonResult RegionDataHandler(DTParameters param)
        {
            try
            {
                var dtsource = new List<RegionData>();

                dtsource = ManageRegion.GetRegionForGrid();

                List<String> columnSearch = new List<string>();

                foreach (var col in param.Columns)
                {
                    columnSearch.Add(col.Search.Value);
                }

                List<RegionData> data = ManageRegion.GetResult(param.Search.Value, param.SortOrder, param.Start, param.Length, dtsource, columnSearch);
                int count = ManageRegion.Count(param.Search.Value, dtsource, columnSearch);
                DTResult<RegionData> result = new DTResult<RegionData>
                {
                    draw = param.Draw,
                    data = data,
                    recordsFiltered = count,
                    recordsTotal = count
                };
                return Json(result);
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message });
            }
        }

        public JsonResult GetEditProjects(int CityID)
        {
            var Response = ManageCity.GetEditProjects(CityID);
            return Json(Response, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetEditRegions(int RegionID)
        {
            FOSDataModel db = new FOSDataModel();
            var Response = ManageRegion.GetEditRegions(RegionID);
            return Json(Response, JsonRequestBehavior.AllowGet);
        }




        //Delete Region Method...
        public int DeleteRegion(int RegionID)
        {
            return FOS.Setup.ManageRegion.DeleteRegion(RegionID);
        }

        #endregion REGION

        #region CITY

        [CustomAuthorize]
        //View Work...
        public ActionResult City()
        {
            // Load Region Data For City Records ...
            var objCity = new CityData();
            int RHID = FOS.Web.UI.Controllers.AdminPanelController.GetRegionalHeadIDRelatedToUser();
            objCity.Regions = FOS.Setup.ManageRegion.GetRegionList(RHID);

            return View(objCity);
        }

        [HttpPost]  
        [ValidateAntiForgeryToken]
        public ActionResult AddUpdateCity([Bind(Exclude = "TID")] CityData newCity)
        {
            Boolean boolFlag = true;
            ValidationResult results = new ValidationResult();
            try
            {
                if (ModelState.IsValid)
                {
                    if (newCity != null)
                    {
                        if (newCity.ID == 0)
                        {
                            CityValidator validator = new CityValidator();
                            results = validator.Validate(newCity);
                            boolFlag = results.IsValid;
                        }

                        if (boolFlag)
                        {
                            int Response = ManageCity.AddUpdateCity(newCity);
                            if (Response == 1)
                            {
                                return Content("1");
                            }
                            else if (Response == 2)
                            {
                                return Content("2");
                            }
                            else
                            {
                                return Content("0");
                            }
                        }
                        else
                        {
                            IList<ValidationFailure> failures = results.Errors;
                            StringBuilder sb = new StringBuilder();
                            sb.Append(String.Format("{0}:{1}", "*** Error ***", "<br/>"));
                            foreach (ValidationFailure failer in results.Errors)
                            {

FOS.Web.UI/Views/Setup/ActivityPurpose.cshtml
@model FOS.Shared.PurposeOfActivityData

@{
    ViewBag.Title = "Region";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- BEGIN PAGE HEADER-->
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN THEME CUSTOMIZER-->

        <!-- END THEME CUSTOMIZER-->
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title"></h3>
        <ul class="breadcrumb">
            <li>
                <a href="#">Setup</a>
                <span class="divider">/</span>
            </li>
            <li>
                <a href="#">Manage ActivityPurpose</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
@using (Ajax.BeginForm("AddUpdateActivityPurpose", "Setup", new AjaxOptions { OnSuccess = "OnSuccess", OnFailure = "OnFailure" }, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)

    <div class="row-fluid">
        <div class="span12">
            <!-- BEGIN SAMPLE FORMPORTLET-->
            <div class="widget green" style="">
                <div class="widget-title">
                    <h4>Manage ActivityPurpose</h4>
                    <span class="tools">
                        @*<a href="javascript:;" class="icon-chevron-down"></a>*@
                        @*<a href="javascript:;" class="icon-remove"></a>*@
                    </span>
                </div>
                <div class="widget-body">
                    <!-- BEGIN FORM-->

                    <div class="control-group">
                        <label class="control-label">ActivityPurpose Name *</label>
                        <div class="controls">
                            @Html.EditorFor(model => model.Name)
                            @Html.ValidationMessageFor(model => model.Name)
                            @Html.HiddenFor(model => model.ID)
                        </div>
                    </div>
                    <div class="control-group">

                        <label class="control-label" for="ShortCode">ActivityPurpose Code *</label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.ShortCode, new { @style = "text-transform: uppercase;" })
                            @Html.ValidationMessageFor(model => model.ShortCode)
                        </div>
                    </div>
                    <div class="control-group" style="border-top: 1px solid #e5e5e5;">
                        <div class="form-actions" style="padding-left: 240px;">
                            <button type="submit" id="btnNew" class="btn btn-primary">
                                <i class="icon-ok icon-white" style="padding-right: 8px;"></i><span id="create">Create</span>
                            </button>
                            <button type="button" class="btn btn-small btn-info" id="btnRefresh"><i class="icon-ban-circle icon-white" style="padding-right: 8px;"></i>Reset</button>
                        </div>
                    </div>

                    <!-- END FORM-->
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>

}
<!-- BEGIN EDITABLE TABLE widget-->
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN EXAMPLE TABLE widget-->
        <div class="widget green">
            <div class="widget-title">
                <h4>View Detail</h4>
                <span class="tools">
                    @*<a href="javascript:;" class="icon-chevron-down"></a>*@
                    @*<a href="javascript:;" class="icon-remove"></a>*@
                </span>
            </div>
            <div class="widget-body">
                <div>
                    <div class="clearfix">
                        @*<div class="btn-group">
                                    <button id="editable-sample_new" class="btn green">
                                        Add New <i class="icon-plus"></i>
                                    </button>
                                </div>*@
                        <div class="btn-group pull-right"></div>
                    </div>
                    <div class="space15"></div>
                    <table class="table table-striped table-hover table-bordered" id="datatab" style="width: 100%;">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.ID)
                                </th>
                                <th style="width: 14% !important">Sr #</th>

                                <th style="width: 38% !important">Activity Purpose Name
                                </th>
                                <th style="width: 38% !important">
                                    Activity Purpose Code
                                </th>
                              
                                <th style="width: 10% !important">Actions</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END EXAMPLE TABLE widget-->
    </div>
</div>
<!-- END EDITABLE TABLE widget-->

<script>

    function GenerateDetailGrid() {
        debugger;
        //$('#datatab tfoot th').each(function () {
        //    $(this).html('<input type="text" />');
        //});
        var oTable = $('#datatab').DataTable({
            "aLengthMenu": [[10, 25, 50, 75, 100], [10, 25, 50, 75, 100]],
            "iDisplayLength": 10,
            "paging": true,
            "pagingType": "full_numbers",
            "serverSide": true,
            "bRetrieve": true,
            "bDestroy": true,
            "autoWidth": true,
            "ajax": {
                "type": "POST",
                "url": '@Url.Action("ActivityPurposeDataHandler", "Setup")',
                "contentType": 'application/json; charset=utf-8',
                'data': function (data) {
                    data.CityID = $('#CityID').val();
                    return data = JSON.stringify(data);
                },

            },
            "fnDrawCallback": function (osetting) {

                var UpdateCheck = "0";
                var DeleteCheck = "0";

                if (UpdateCheck == "@HttpContext.Current.Session["UpdateCheck"]") { $(".edit").css("display", "none"); }
                else {
                    $(".edit").on("click", function () {

                        ClearForm();

                        $('#RegionID').val($(this).attr("data-id"));
                        $('#create').text('Update');

                        $("#Name").val($(this).attr("data-name"));
                        $("#ShortCode").val($(this).attr("data-shortcode"));

                        $('html, body').animate({
                            scrollTop: $("#main-content").offset().top
                        }, 500);
                        $("#Name").focus();

                    });
                }

                if (UpdateCheck == "@HttpContext.Current.Session["DeleteCheck"]") { $(".delete").css("display", "none"); }
                else {
                    $(".delete").on("click", function () {
                        debugger;
                        var regionID = $(this).attr("data-id");

                        // confirm dialog
                        alertify.confirm("Are You Sure You Want To Delete This Record ?  ", function (e) {
                            if (e) {

                                $.ajax({
                                    type: "POST",
                                    url: "@Url.Action("DeleteActivityPurpose", "Setup")",
                                    data: { RegionID: regionID },
                                    success: function (data) {

                                        if (data == "0") {
                                            alertify.success('Record Deleted Successfully');
                                            var table = $('#datatab').DataTable();
                                            table.row(this).remove().draw(false);
                                        }

                                        else { alertify.error('This Region Assigned To Regional Head. If You Want To Delete This Region Then First Delete Regional Head Which Assign To This Region.'); }
                                    }

                                });

                            } else { }
                        });

                    });
                }
            },

            "fnRowCallback": function (nRow, aData, iDisplayIndex) {
                $("td:first", nRow).html(iDisplayIndex + 1);
                return nRow;
            },
            "oLanguage": { "sSearch": "Search Area : " },
            "sDom": 'lftipr',
            "processing": true,
            "deferRender": true,
            "bSelect": true,
            "columns": [
           { "data": "ID", "bVisible": false },
           { "data": "Name", "bSortable": false },
           { "data": "Name" },
           { "data": "ShortCode" },
           {
               "sClass": "center-align-td",
               "mData": null,
               "bSortable": false,
               "mRender": function (data, type, row) {
                   return '<button class="btn btn-success edit" data-id=' + row.ID + ' data-name=' + '"' + row.Name + '"' + ' data-shortcode=' + row.ShortCode + '>' + '<i class=icon-pencil></i>' + '</button>&nbsp;<button class="btn btn-info delete" data-id=' + row.ID + '>' + '<i class=icon-trash></i>' + '</button>';
               }
           }
            ],
            "order": [4, "asc"]

        });

    }

    $(document).ready(function () {

        $("#liSetup,#liRegion").addClass("active");

        var WriteCheck = "0";

        if (WriteCheck == "@HttpContext.Current.Session["WriteCheck"]") {
            // $("#btnNew").css("display", "none");
            $("#btnNew").attr("disabled", true);
        }
        else {
        }

        $("#btnRefresh").click(function () {
            ClearForm();
        });

        GenerateDetailGrid();

    });
</script>
<script type="text/javascript">

    function ClearForm() {
        $('#Name').val('');
        $('#ShortCode').val('');
        $('#ID').val(0);
        $('#create').text('Create');
    }

    function OnSuccess(response) {
        if (response == "1") {
            alertify.success("Region Saved Successfully");
            $('#create').text('Create');
            var dt = $('#datatab').DataTable();
            dt.ajax.reload();
            ClearForm();
        }
        else if (response == "0") {
            alertify.error("Unable To Save Region.");
        }
        else if (response == "2") {
            alertify.error("Region Code Already Exist");
        }
        else {
            alertify.error(response);
        }

    }

    function OnFailure(response) {
        if (response.status == 422) {
            var errors = JSON.parse(response.responseText);
            alertify.error(errors.errors);
        }
        else {
            alertify.error(response);
        }
    }
</script>